### ISSUE TITLE
Left out a bunch of images

### ISSUE THREAD

**Issue by BrindleWolf** [danielmonettelli/netmaui-mitawi-app-challenge#16]
You left out a bunch of images and there seems to be some issues with formatting the data which is displayed.
I get 302.63 degrees in the main section and a long string of numbers along the bottom of the lower list of hourlies. Wind, humidity and rain chance all work fine. It always says "Updating" at the top, as well.

I'm going to see if I can fix these, but the missing icons is rough as I don't know what font you used, so can't just add the missing ones to the CustomFontIcons list.

**Comment by BrindleWolf** [comment]
False alarm on the icons, my MauiProgram didn't save, so no font injection.
Everything except the large 10 scale image in the main section works now.

**Comment by danielmonettelli** [comment]
Hello @BrindleWolf, my apologies for the delayed response. Upon reviewing the issue, I've found that the images weren't displaying correctly in Windows due to the absence of the ".png" extension in the `source` attribute of the image controls, and also because dimensions weren't specified for each `image` control. I've taken the necessary steps to rectify this error. I sincerely appreciate your understanding, and thank you for bringing this issue to my attention.
